export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

// DASHBOARDS
export const DEACONS_IMAGE = "DEACONS_IMAGE";
export const TRUSTEE_IMAGE = "TRUSTEE_IMAGE";
export const PASTOR_WIFE = "PASTOR_WIFE";
export const PASTOR_WIFE_IMAGE = "PASTOR_WIFE_IMAGE";
export const CHURCH_IMAGE = "CHURCH_IMAGE";
export const CHURCH_BANNER_IMAGE = "CHURCH_BANNER_IMAGE";
export const CHURCH_LOGO = "CHURCH_LOGO";
export const GALLERY_IMAGES = "GALLERY_IMAGES";


// UPDATE CHURCH
export const UPDATE_CHURCH_REQUEST = "UPDATE_CHURCH_REQUEST";
export const UPDATE_CHURCH_SUCCESS = "UPDATE_CHURCH_SUCCESS";
export const UPDATE_CHURCH_RESET = "UPDATE_CHURCH_RESET";
export const UPDATE_CHURCH_FAIL = "UPDATE_CHURCH_FAIL";

export const REMOVE_CHURCH_FAIL = "REMOVE_CHURCH_FAIL";
export const REMOVE_CHURCH_SUCCESS = "REMOVE_CHURCH_SUCCESS";

export const REMOVE_SONG_SUCCESS = "REMOVE_SONG_SUCCESS";
export const REMOVE_SONG_FAIL = "REMOVE_SONG_FAIL";

export const REMOVE_PAST_SERVICE_SUCCESS = "REMOVE_PAST_SERVICE_SUCCESS";
export const REMOVE_PAST_SERVICE_FAIL = "REMOVE_PAST_SERVICE_FAIL";

export const REMOVE_DEACON_SUCCESS = "REMOVE_DEACON_SUCCESS";
export const REMOVE_DEACON_FAIL = "REMOVE_DEACON_FAIL";

export const REMOVE_TRUSTEE_SUCCESS = "REMOVE_TRUSTEE_SUCCESS";
export const REMOVE_TRUSTEE_FAIL = "REMOVE_TRUSTEE_FAIL";

export const REMOVE_LIVE_SERVICE_SUCCESS = "REMOVE_LIVE_SERVICE_SUCCESS";
export const REMOVE_LIVE_SERVICE_FAIL = "REMOVE_LIVE_SERVICE_FAIL";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_RESET = "UPDATE_AVATAR_RESET";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";
